.PHONY: all test-float-basic test-float-compare test-float-operations

all: test-float-basic  test-float-compare  test-float-operations test-float-basic-fail

test-float-basic:
	${MAKE} -C test-float-basic

test-float-compare:
	${MAKE} -C test-float-compare

test-float-operations:
	${MAKE} -C test-float-operations

test-float-basic-fail:
	${MAKE} -C test-float-basic-fail
